# Workflow para desplegar una aplicación Nuxt a GitHub Pages
name: Deploy Nuxt site to Pages

on:
  # Se ejecuta al hacer push a la rama principal
  push:
    branches: ["main"]

  # Permite ejecutar manualmente desde la pestaña Actions
  workflow_dispatch:

# Establece permisos del GITHUB_TOKEN para permitir despliegue a GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue concurrente
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Trabajo de construcción
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: nuxt
      - name: Install dependencies
        run: npm install
      - name: Static HTML export con Nuxt
        run: npx nuxt build --preset github_pages
        env:
          # CRÍTICO: Establecer la URL base para GitHub Pages
          NUXT_APP_BASE_URL: /ActividApp/
          # Variables de Supabase
          NUXT_SUPABASE_URL: ${{ secrets.NUXT_SUPABASE_URL }}
          NUXT_SUPABASE_KEY: ${{ secrets.NUXT_SUPABASE_KEY }}
      - name: Add .nojekyll file
        run: touch .output/public/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public

  # Trabajo de despliegue
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
